version: "3"

services:
  web:
    build: .
    command: /code/run_web.sh
    volumes:
      - .:/code
    restart: always
    expose:
      - 8000
    env_file:
      - secrets.env

  nginx:
    build:
      context: ./nginx/
      dockerfile: staging.Dockerfile
    ports:
      - 80:80
    environment:
      - DJANGO_HOST=web
    links:
      - web:web
    restart: always
